---
sidebar: sidebar 
permalink: task-manage-private-aws-cloud-insights.html 
keywords: activate,license, licensing, install, request capacity, link subscription, digital wallet, keystone flex, digital wallet, bluexp digital wallet 
summary: 管理您的通用和超大規模特定、端到端私人優惠流程以及適用於 AWS、Azure 和 Google Cloud 的NetApp智慧服務接受和啟用指南。 
---
= 接受並配置NetApp Cloud Insights的 AWS Marketplace 專屬優惠
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 AWS 控制台中接受NetApp Cloud Insights的 Marketplace 專屬優惠。將 AWS 訂閱連接到Cloud Insights工作環境。

.開始之前
* 與NetApp銷售人員合作創建私人優惠並獲取優惠連結。
* 與NetApp銷售人員合作建立Cloud Insights工作環境並新增具有 *所有者* 角色的電子郵件。
* 確保您擁有所需的link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groupspolicies.html["AWS Marketplace 權限"]




== 在 AWS 主控台中接受私人優惠

[IMPORTANT]
====
您必須完成所有步驟才能啟動您的私人優惠。跳過這些步驟可能會導致啟動問題或計費錯誤，包括重複收費。

====
.步驟
. 點擊NetApp銷售團隊提供的私人優惠啟動連結。該連結應類似於以下內容：
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
[NOTE]
====
如果您沒有收到啟動鏈接，您可以在 AWS 控制台中查看所有私人優惠。

** 所需的託管策略：*AWSMarketplaceRead-only*、*AWSMarketplaceManageSubscriptions* 或 *AWSMarketplaceFullAccess*
** 如果使用自訂 IAM 策略： `aws-marketplace:ListPrivateListings`和 `aws-marketplace:ViewSubscriptions`


====
. 您將被重定向到 AWS Marketplace 來查看並接受私人優惠。
+
[NOTE]
====
私人報價是在公開清單的基礎上建立的。使用「*優惠選擇*」下拉式選單在公開優惠和私人優惠之間切換。

====
. 查看私人優惠詳情並驗證其是否符合您的協議。
+
.. 如果資訊不正確，則不接受。聯絡您的NetApp銷售團隊修改報價。
.. 一旦您選擇*訂閱*，計費就開始了。
+
[NOTE]
====
AWS 中存在兩種私人優惠類型：

*** *按需使用*
+
**** 定價訊息
**** 法律條款


*** *合約*
+
**** 持續時間和日期
**** 續訂設定
**** 合約選項
**** 合約總價




對於合約要約，請輸入商定的管理單位數量。

====


. 接受私人優惠：
+
.. 如需隨選使用，請點選*訂閱*。
.. 對於合約要約，請輸入每項服務的管理單位數量，然後按一下「建立合約」。


. 接受後，橫幅會確認您已成功訂閱並提供後續步驟。
. 點擊“設定您的帳戶”。這會將您重新導向至NetApp Cloud Insights來設定您的 Marketplace 訂閱。
+
[NOTE]
====
如果報價被接受但註冊未完成，請返回產品頁面。系統將提示您完成註冊。

對於合約優惠，請點擊「查看購買選項」以查看私人優惠，然後選擇「設定您的帳戶」。

====




== 將訂閱連接到Cloud Insights

.步驟
. 您將被重新導向至 https://cloudinsights.netapp.com[]並提示您使用BlueXP帳號登入。
. 使用具有 *所有者* 角色的帳戶登入。該訂閱與您的Cloud Insights工作環境相關聯。
+
[NOTE]
====
每次訂閱僅需執行此步驟一次。續訂和附加元件將自動套用。

====
. 訂閱現已連線。

